import Foundation

struct Recipe: Identifiable, Codable, Hashable {
    var id: UUID = .init()
    var title: String
    var servings: Int
    var totalMinutes: Int
    var ingredients: [RecipeIngredient]
    var steps: [String]
    var equipment: [String] = []
    var tags: [String] = []
    var detectedIngredients: String? = nil  // Optional: ingredients detected from fridge photo
    
    // Meal Prep metadata (optional, generated by AI)
    var shelfLifeDays: Int? = nil  // Storage duration in fridge (days)
    var isFreezable: Bool? = nil   // Can be frozen
    var storageNote: String? = nil // User-friendly storage note
    
    // Nutritional information per serving (optional, calculated by AI)
    var caloriesPerServing: Int? = nil
    var proteinPerServing: Int? = nil
    var carbsPerServing: Int? = nil
    var fatPerServing: Int? = nil
    
    enum CodingKeys: String, CodingKey {
        case title
        case servings
        case totalMinutes = "total_minutes"
        case ingredients
        case steps
        case equipment
        case tags
        case detectedIngredients = "detected_ingredients"
        case shelfLifeDays = "shelf_life_days"
        case isFreezable = "is_freezable"
        case storageNote = "storage_note"
        case caloriesPerServing = "calories_per_serving"
        case proteinPerServing = "protein_per_serving"
        case carbsPerServing = "carbs_per_serving"
        case fatPerServing = "fat_per_serving"
    }
}

struct RecipeIngredient: Identifiable, Codable, Hashable {
    var id: UUID = .init()
    var name: String
    var quantity: Double
    var unit: String
    var category: String
    var isOnSale: Bool = false  // Indicates if ingredient is on sale in weekly flyers
    
    enum CodingKeys: String, CodingKey {
        case name
        case quantity
        case unit
        case category
        case isOnSale = "is_on_sale"
    }
    
    // Custom decoder for backward compatibility with old data without isOnSale
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        name = try container.decode(String.self, forKey: .name)
        quantity = try container.decode(Double.self, forKey: .quantity)
        unit = try container.decode(String.self, forKey: .unit)
        category = try container.decode(String.self, forKey: .category)
        // Decode isOnSale with a default value of false if missing
        isOnSale = try container.decodeIfPresent(Bool.self, forKey: .isOnSale) ?? false
    }
}
